version: 0.1
templates:
- name: tf-aliyunecs-ansible
  terraform:
    workdir: ./
    save_state: true
    instance_number: 1
    instance_type: ecs.n2.small
  repo_branch: master
  description: "\u8BE5\u6A21\u5757\u4F1A\u5728\u963F\u91CC\u4E91\u670D\u52A1\u4E0A\
    \u521B\u5EFAecs\u670D\u52A1\u5668\uFF0C\u5E76\u5728\u8BE5Ecs\u670D\u52A1\u5668\
    \u914D\u7F6E\u5E76\u542F\u52A8nginx \u670D\u52A1\u3002"
  timeout: 300
  ansible:
    workdir: ./ansible/
    playbook: playbook.yml
