version: 0.1
templates:
- name: tf-aliyunecs-ansible
  terraform:
      # 工作目录，以下所有配置中的文件相对路径都是基于该目录
    workdir: ./
    save_state: true
  env:
    ALICLOUD_ACCESS_KEY: ''
    ALICLOUD_SECRET_KEY: ''
    ALICLOUD_REGION: cn-beijing
